# server:
#   port: 8080
# spring:
#   jpa:
#     hibernate:
#       ddl-auto: create-drop
#     database-platform: org.hibernate.dialect.H2Dialect
#     defer-datasource-initialization: true
#   datasource:
#     url: jdbc:h2:mem:memdb
#     driver-class-name: org.h2.Driver
#     username: sa
#     password: password
#   h2:
#     console.enabled: true

server:
  port: 8083
spring:
  jpa:
    hibernate:
      jdbc:
        lob:
          non_contextual_creation: true
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    defer-datasource-initialization: true
  datasource:
    #url: jdbc:postgresql://18.144.30.236:5434/postgres
    url: jdbc:postgresql://localhost:5433/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  h2:
    console.enabled: true



    
